/* eslint-disable @typescript-eslint/no-require-imports */
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("accountingApi", {
    getDbInfo: () => ipcRenderer.invoke("db:get-info"),
    chooseDbDirectory: () => ipcRenderer.invoke("db:choose-directory"),
    setDbDirectory: (nextDirectory) => ipcRenderer.invoke("db:set-directory", nextDirectory),
    listAccounts: () => ipcRenderer.invoke("accounts:list"),
    addAccount: (code, name) => ipcRenderer.invoke("accounts:add", { code, name }),
    listOrganizations: () => ipcRenderer.invoke("organizations:list"),
    createOrganization: (organization) => ipcRenderer.invoke("organizations:create", organization),
    updateOrganization: (organization) => ipcRenderer.invoke("organizations:update", organization),
    deleteOrganization: (organizationId) => ipcRenderer.invoke("organizations:delete", organizationId),
    listClients: () => ipcRenderer.invoke("clients:list"),
    createClient: (client) => ipcRenderer.invoke("clients:create", client),
    updateClient: (client) => ipcRenderer.invoke("clients:update", client),
    deleteClient: (clientId) => ipcRenderer.invoke("clients:delete", clientId),
    listAllClientAccounts: () => ipcRenderer.invoke("client-accounts:list-all"),
    listClientAccounts: (clientId) => ipcRenderer.invoke("client-accounts:list", clientId),
    createClientAccount: (account) => ipcRenderer.invoke("client-accounts:create", account),
    deleteClientAccount: (accountId) => ipcRenderer.invoke("client-accounts:delete", accountId),
    listCurrencies: () => ipcRenderer.invoke("currencies:list"),
    createCurrency: (currency) => ipcRenderer.invoke("currencies:create", currency),
    updateCurrency: (currency) => ipcRenderer.invoke("currencies:update", currency),
    deleteCurrency: (currencyId) => ipcRenderer.invoke("currencies:delete", currencyId),
    enableCurrency: (currencyId) => ipcRenderer.invoke("currencies:enable", currencyId),
    disableCurrency: (currencyId) => ipcRenderer.invoke("currencies:disable", currencyId),
    setMainCurrency: (currencyId) => ipcRenderer.invoke("currencies:set-main", currencyId),
    listTransactions: () => ipcRenderer.invoke("transactions:list"),
    createTransaction: (transaction) => ipcRenderer.invoke("transactions:create", transaction),
    updateTransaction: (transaction) => ipcRenderer.invoke("transactions:update", transaction),
    deleteTransaction: (transactionId) => ipcRenderer.invoke("transactions:delete", transactionId),
});
